### ISSUE TITLE
print() needs to be revised

### ISSUE THREAD

**Issue by Gennadiyev** [Gennadiyev/kun-calculator#1]
There should be a better way to display messages.

**Comment by Gennadiyev** [comment]
All related issues can be discussed below.

**Comment by Richardn2002** [comment]
WHAT DO YOU THINK I CAN DO THIS???

**Comment by Gennadiyev** [comment]
Will try to implement a new way to display logs. Using a non-editable `EditText` element can be a solution.

**Comment by Richardn2002** [comment]
@Gennadiyev just call it Console

**Comment by Gennadiyev** [comment]
Done for the issue. Added an element called `printer` to handle outputs.
